# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z7_9ppU9aZan-nFZLxHEaiOQ0-dlsbCY
"""

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
import matplotlib.pyplot as plt

def activation_function(z):
    return np.where( z>=0, 1, -1  )

def fit(X_train, y_train, learning_rate=0.1, epochs=1000):
    weights = np.zeros(X_train.shape[1])
    bias = 0

    for _ in range(epochs):
        for idx, x_i in enumerate(X_train):
            y_pred = activation_function(np.dot(x_i, weights) + bias)
            update = learning_rate * (y_train[idx] - y_pred)
            weights += update * x_i
            bias += update
    return weights, bias

def predict(X, weights, bias):
    return activation_function(np.dot(X, weights) + bias)

def accuracy(y_true, y_pred):
    return np.sum(y_true == y_pred) / len(y_true)

# Base patterns for L and T
base_L = np.array([1,0,0,0, 1,0,0,0, 1,0,0,0, 1,1,1,1])
base_T = np.array([1,1,1,1, 0,0,1,0, 0,0,1,0, 0,0,1,0])

def generate_variations(base_pattern, n_samples=50):
    samples = []
    for _ in range(n_samples):
        p = base_pattern.copy()
        # Shift rows slightly left/right
        shift = np.random.choice([-1, 0, 1])
        if shift != 0:
            for r in range(4):
                row = p[r*4:(r+1)*4]
                row = np.roll(row, shift)
                p[r*4:(r+1)*4] = row
        samples.append(p)
    return np.array(samples)

# Generate dataset
L_samples = generate_variations(base_L, 50)
T_samples = generate_variations(base_T, 50)
X = np.vstack((L_samples, T_samples))
y = np.array([1]*50 + [-1]*50)  # L=1, T=-1

# Shuffle and split for training/testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train perceptron
weights, bias = fit(X_train, y_train)

# Test accuracy
y_pred = predict(X_test, weights, bias)
print("Accuracy:", accuracy(y_test, y_pred))

# Evaluate
y_pred = predict(X_test, weights, bias)
print("Accuracy:", accuracy(y_test, y_pred))
print("Weights:", weights)
print("Bias:", bias)















